version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.10.0

    working_directory: /go/src/github.com/mriedmann/rocketchat-cli

    environment:
      GOCACHE: "/tmp/go/cache"
      DEP_VERSION: 0.5.1

    steps:
      - checkout

      - restore_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/mriedmann/rocketchat-cli/vendor

      - run:
          name: download-libraries
          command: |
            if [ ! -d /go/src/github.com/mriedmann/rocketchat-cli/vendor ]; then
                curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o /go/bin/dep
                chmod +x /go/bin/dep
                /go/bin/dep ensure
            fi

      - save_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/mriedmann/rocketchat-cli/vendor

      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
          paths:
            - /tmp/go/cache

      - run:
          name: test
          command: |
            mkdir -p $GOCACHE
            go build -v
            go test -p 6 -race ./...

      - run:
          name: install
          command: |
            mkdir -p $GOCACHE
            go install -v ./...

      - store_artifacts:
          path: /go/bin/rocketchat-cli

      - save_cache:
          key: build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - /tmp/go/cache
